### ISSUE TITLE
AWS RDS security problem

### ISSUE THREAD

**Issue by m4a1carbin4** [FixIt-Dev-Team/Server_TtuckTtak#23]
application.yml 파일 노출에 따른 RDS 접속 admin 권한 노출 관련 문제.

**Comment by m4a1carbin4** [comment]
application.yml 파일 내 DB 관련 데이타 secret.yml이전 처리.
관련 secret.yml 업데이트 진행.

**Comment by destiny3912** [comment]
해결 완료로 인한 클로징
