### ISSUE TITLE
View API

### ISSUE THREAD

**Issue by destiny3912** [FixIt-Dev-Team/Server_TtuckTtak#31]
- [x] 메인 페이지 뷰
- [x] 설정 뷰
- [x] 프로필 설정 뷰

**Comment by destiny3912** [comment]
페이지 레퍼런스는 노션을 참조

**Comment by m4a1carbin4** [comment]
작업 내역 확인

**Comment by m4a1carbin4** [comment]
진 짜 로 날림 그 자체로 붙인 수정 패치니 무슨 문제가 벌어질지 알지못함. -> 확인 부탁 
+ 메인 페이지 뷰는 지금 보니깐 유저 히스토리 테이블 나오기까진 멀 진행 못할거 같음.
+ 프로필 설정 페이지 데이터 전송떄 이 포스트 참조 부탁함.
[포스트](https://velog.io/@songs4805/Spring-Controller%EC%97%90%EC%84%9C-MultipartFile-Dto%EB%A5%BC-%ED%95%A8%EA%BB%98-%EC%9A%94%EC%B2%AD%ED%95%98%EA%B8%B0)
+ 프로필 설정 페이지에 일단 이미지 전송 관련 코드는 정돈 해둬야 프론트가 편할거 같아서 우선 파일 전송하고 로컬에 심어두는 정도까지만 해둠 차후에 S3로 박는 로직 추가 필요.

**Comment by m4a1carbin4** [comment]
ADD S3 logic for save user Profile IMG

**Comment by destiny3912** [comment]
구현 완료
