### ISSUE TITLE
AuthService 리펙토링

### ISSUE THREAD

**Issue by namsh1125** [FixIt-Dev-Team/Server_TtuckTtak#34]
- [x] Test code에 있어야 할 로직이 service 단에 있는 코드 수정 (제대로 추가되었는지 확인하는 코드 제거)
- [x] 중복 코드 추출 - 토큰 발행
- [x] 중복 코드 추출 - 로그인 처리
- [x] Post sign up dto 정리

**Comment by m4a1carbin4** [comment]
AuthService 내부 
public PostLoginRes login(String userID, String userPW) 메소드 내부 수정 요망.

**Comment by namsh1125** [comment]
버그 수정 완료
