### ISSUE TITLE
gitHubActionDeploy

### ISSUE THREAD

**Issue by destiny3912** [FixIt-Dev-Team/Server_TtuckTtak#4]

**Comment by m4a1carbin4** [comment]
깃허브 액션으로 gradle 빌드 진행 (secret.yml 자동 생성 : 레포지토리 시크릿 참조) -> 빌드 완료된 내용을 AWS S3로 업로드 -> AWS CodeDeploy 트리거 작동 : github Action 마무리 -> CodeDeploy 단계에서 S3에서 빌드된 파일 EC2로 업로드 -> 배포 과정에서 커스텀된 스크립트로 서버 시작처리.

**Comment by m4a1carbin4** [comment]
auto deploy failed : deploy.sh edit
