### ISSUE TITLE
Solution API

### ISSUE THREAD

**Issue by destiny3912** [FixIt-Dev-Team/Server_TtuckTtak#72]
- [x] 엔트리 조회
- [x] 상세 조회
- [x] 바이패스 넘어가기

**Comment by m4a1carbin4** [comment]
작업 시작

**Comment by m4a1carbin4** [comment]
작업 명세 기반으로 관련 로직 처리 내용 마무리 하여 추가. 현재 테스트 데이터 추가중에 있으나 로직 체크용 중간리뷰 바람. 
@destiny3912 @namsh1125
